GET http://localhost:3001/api/blogs

###
# GET http://localhost:3001/api/info

###
# GET http://localhost:3001/api/blogs/3

####################################
DELETE http://localhost:3001/api/blogs/62a48487fcfeca016e7d2006

###
DELETE http://localhost:3001/api/blogs/62a48487fcfeca016e7d2006huhu

####################################
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "the call of the wild",
  "author": "Jack London",
  "url": "hihihaha.com",
  "likes": 8
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "",
  "author": "Jack London",
  "url": "hihihaha.com",
  "likes": 8
}

#################################### WITH USER
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "the call of the wild",
  "author": "Jack London",
  "url": "hihihaha.com",
  "likes": 8,
  "userId": "62a4c7abc8e6ad6f4fc0ce69"
}
#################################### WITH TOKEN
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhpaGloYWhhIiwiaWQiOiI2MmE1YTNhNGJlZjE3MjJiZTNlNWM1OTciLCJpYXQiOjE2NTUwMjg3Nzl9.UCRIfxkk0lyJijm4L47tzejfMhFy98FlAAYv5LOad-A

{
  "title": "the call of the wild",
  "author": "Jack London",
  "url": "hihihaha.com",
  "likes": 8
}

####################################
PUT http://localhost:3001/api/blogs/62a499abf30d8208bb422d29
Content-Type: application/json

{
  "title": "the call of the wild",
  "author": "Jack London hihihaha",
  "url": "hihihaha.com",
  "likes": 8
}
###
PUT http://localhost:3001/api/blogs/62a499abf30d8208bb422d29
Content-Type: application/json

{
  "title": "",
  "author": "Jack London hihihaha",
  "url": "hihihaha.com",
  "likes": 8
}
