GET http://localhost:3001/api/blogs

###
# GET http://localhost:3001/api/info

###
# GET http://localhost:3001/api/blogs/3

###
# DELETE http://localhost:3001/api/blogs/3

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "the call of the wild",
  "author": "Jack London",
  "url": "hihihaha.com",
  "likes": 8
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "",
  "author": "Jack London",
  "url": "hihihaha.com",
  "likes": 8
}
###
# PUT http://localhost:3001/api/blogs/62a1062e8eed5e181d5c04f6
# Content-Type: application/json

# {
#     "name": "testtest",
#     "number": "01234"
# }
