GET http://localhost:3001/api/users

###
GET http://localhost:3001/api/users/3

####################################
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "user1",
  "name": "one",
  "password": "passuser1"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "user2",
  "name": "two",
  "password": "passuser2"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "",
  "name": "three",
  "password": "passuser3"
}

####################################
DELETE http://localhost:3001/api/users/62a48487fcfeca016e7d2006

###
DELETE http://localhost:3001/api/users/62a48487fcfeca016e7d2006huhu