GET http://localhost:3001/api/users

###
GET http://localhost:3001/api/users/3

####################################
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "hihihaha",
  "name": "hiha",
  "password": "hihihaha"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "",
  "name": "hiha",
  "password": "123"
}

####################################
DELETE http://localhost:3001/api/users/62a48487fcfeca016e7d2006

###
DELETE http://localhost:3001/api/users/62a48487fcfeca016e7d2006huhu

####################################
PUT http://localhost:3001/api/users/62a499abf30d8208bb422d29
Content-Type: application/json

{
  "title": "the call of the wild",
  "author": "Jack London hihihaha",
  "url": "hihihaha.com",
  "likes": 8
}
###
PUT http://localhost:3001/api/users/62a499abf30d8208bb422d29
Content-Type: application/json

{
  "title": "",
  "author": "Jack London hihihaha",
  "url": "hihihaha.com",
  "likes": 8
}
